version: '3.4'

services:
  nodejs:
    build: 
      context: .
    image: darioravello/node-backend-enviame
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=enviame
      - MYSQL_PASS=enviamepass
      - MYSQL_DB=enviame_db
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "3000:3000"
    container_name: node-backend
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=enviame
      - MYSQL_PASSWORD=enviamepass 
      - MYSQL_DATABASE=enviame_db
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin
networks:
  frontend:
  backend: